-- Rejestr Umów Fundacji
-- Obsługuje SQLite i MySQL (różnice oznaczone komentarzami)

-- USERS
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    microsoft_id VARCHAR(255),
    role VARCHAR(50) DEFAULT 'viewer', -- admin / editor / viewer
    is_active INTEGER DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- UMOWA ZLECENIE
CREATE TABLE IF NOT EXISTS umowy_zlecenie (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'projekt',
    imie_nazwisko VARCHAR(255),
    pesel VARCHAR(11),
    adres TEXT,
    seria_nr_dowodu VARCHAR(50),
    urzad_skarbowy VARCHAR(255),
    rachunek_bankowy VARCHAR(50),
    przedmiot_zlecenia TEXT,
    data_zawarcia DATE,
    data_rozpoczecia DATE,
    data_zakonczenia DATE,
    wynagrodzenie_brutto DECIMAL(12,2),
    stawka_kwota DECIMAL(10,2),
    typ_stawki VARCHAR(20),         -- godzinowo / ryczalt
    liczba_godzin_planowana DECIMAL(8,2),
    sposob_rozliczenia VARCHAR(20),
    termin_platnosci VARCHAR(100),
    zus_skladki INTEGER DEFAULT 0,
    tytul_ubezpieczenia VARCHAR(255),
    zwolnienie_wiek INTEGER DEFAULT 0,
    zaliczka_podatek DECIMAL(10,2),
    kup VARCHAR(10),                -- 20 / 50 / brak
    numer_projektu VARCHAR(255),
    opiekun VARCHAR(255),
    wymagany_rachunek INTEGER DEFAULT 0,
    data_zl_rachunku DATE,
    forma_podpisania VARCHAR(20),   -- papierowa / elektroniczna
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    m365_konto INTEGER DEFAULT 0,
    m365_login VARCHAR(255),
    m365_user_id VARCHAR(255),
    m365_konto_aktywne INTEGER DEFAULT 0,
    m365_data_utworzenia DATETIME,
    m365_licencja_przypisana INTEGER DEFAULT 0,
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- UMOWA O ŚWIADCZENIE USŁUG
CREATE TABLE IF NOT EXISTS umowy_uslugi (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'projekt',
    nazwa_wykonawcy VARCHAR(255),
    nip_pesel VARCHAR(20),
    adres TEXT,
    rachunek_lub_faktura VARCHAR(255),
    przedmiot_uslugi TEXT,
    zakres_uslug TEXT,
    data_zawarcia DATE,
    data_rozpoczecia DATE,
    data_zakonczenia DATE,
    czas_nieokreslony INTEGER DEFAULT 0,
    okres_wypowiedzenia VARCHAR(100),
    wartosc_netto DECIMAL(12,2),
    wartosc_brutto DECIMAL(12,2),
    stawka_vat VARCHAR(10),
    waluta VARCHAR(10) DEFAULT 'PLN',
    harmonogram_platnosci VARCHAR(50), -- jednorazowo / miesięcznie / transze
    termin_platnosci_dni INTEGER,
    numer_projektu VARCHAR(255),
    wymagana_faktura INTEGER DEFAULT 1,
    opiekun VARCHAR(255),
    wymagany_protokol INTEGER DEFAULT 0,
    data_odbioru DATE,
    forma_podpisania VARCHAR(20),
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    zalaczniki VARCHAR(1000),
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- UMOWA WOLONTARIACKA
CREATE TABLE IF NOT EXISTS umowy_wolontariat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'projekt',
    imie_nazwisko VARCHAR(255),
    pesel VARCHAR(11),
    adres TEXT,
    telefon VARCHAR(20),
    email VARCHAR(255),
    data_urodzenia DATE,
    niepelnoletni INTEGER DEFAULT 0,
    zgoda_opiekuna VARCHAR(500),
    przedmiot_porozumienia TEXT,
    miejsce_wolontariatu VARCHAR(255),
    data_zawarcia DATE,
    data_rozpoczecia DATE,
    data_zakonczenia DATE,
    bezterminowa INTEGER DEFAULT 0,
    godzin_tygodniowo DECIMAL(5,2),
    godzin_przepracowanych DECIMAL(8,2) DEFAULT 0,
    ubezpieczenie_nnw INTEGER DEFAULT 0,
    numer_polisy_nnw VARCHAR(100),
    ubezpieczenie_oc INTEGER DEFAULT 0,
    szkolenie_bhp INTEGER DEFAULT 0,
    data_szkolenia_bhp DATE,
    zwrot_kosztow INTEGER DEFAULT 0,
    zwrot_kosztow_opis TEXT,
    opiekun VARCHAR(255),
    projekt_program VARCHAR(255),
    forma_podpisania VARCHAR(20),
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    m365_konto INTEGER DEFAULT 0,
    m365_login VARCHAR(255),
    m365_user_id VARCHAR(255),
    m365_konto_aktywne INTEGER DEFAULT 0,
    m365_data_utworzenia DATETIME,
    m365_licencja_przypisana INTEGER DEFAULT 0,
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- UMOWA O DZIEŁO
CREATE TABLE IF NOT EXISTS umowy_dzielo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'projekt',
    imie_nazwisko VARCHAR(255),
    pesel VARCHAR(11),
    adres TEXT,
    urzad_skarbowy VARCHAR(255),
    rachunek_bankowy VARCHAR(50),
    opis_dziela TEXT,
    termin_oddania DATE,
    data_zawarcia DATE,
    wynagrodzenie_brutto DECIMAL(12,2),
    kup50 INTEGER DEFAULT 0,
    zaliczka_podatek DECIMAL(10,2),
    prawa_autorskie INTEGER DEFAULT 0,
    zakres_praw TEXT,
    wymagany_protokol INTEGER DEFAULT 0,
    data_odbioru DATE,
    dzielo_przyjete INTEGER DEFAULT 0,
    data_zl_rachunku DATE,
    numer_projektu VARCHAR(255),
    opiekun VARCHAR(255),
    forma_podpisania VARCHAR(20),
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    m365_konto INTEGER DEFAULT 0,
    m365_login VARCHAR(255),
    m365_user_id VARCHAR(255),
    m365_konto_aktywne INTEGER DEFAULT 0,
    m365_data_utworzenia DATETIME,
    m365_licencja_przypisana INTEGER DEFAULT 0,
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- UMOWA O PRACĘ
CREATE TABLE IF NOT EXISTS umowy_praca (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'obowiązująca',
    imie_nazwisko VARCHAR(255),
    pesel VARCHAR(11),
    adres TEXT,
    seria_nr_dowodu VARCHAR(50),
    urzad_skarbowy VARCHAR(255),
    rachunek_bankowy VARCHAR(50),
    stanowisko VARCHAR(255),
    dzial_projekt VARCHAR(255),
    wymiar_etatu VARCHAR(20),
    rodzaj_umowy VARCHAR(50),       -- próbny / czas określony / nieokreślony
    data_zawarcia DATE,
    data_rozpoczecia DATE,
    data_zakonczenia DATE,
    wynagrodzenie_brutto DECIMAL(12,2),
    skladniki_wynagrodzenia TEXT,
    urlop_wymiar INTEGER,
    urlop_zalegly INTEGER DEFAULT 0,
    okres_wypowiedzenia VARCHAR(100),
    ppk INTEGER DEFAULT 0,
    pit2 INTEGER DEFAULT 0,
    badania_data_waznosci DATE,
    bhp_data_waznosci DATE,
    klauzula_rodo INTEGER DEFAULT 0,
    opiekun_przelozony VARCHAR(255),
    forma_podpisania VARCHAR(20),
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    aneksy TEXT,
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- INNA UMOWA
CREATE TABLE IF NOT EXISTS umowy_inne (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numer_umowy VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'projekt',
    typ_umowy VARCHAR(255),
    strona_umowy VARCHAR(255),
    pesel_nip_krs VARCHAR(50),
    adres TEXT,
    przedmiot_umowy TEXT,
    data_zawarcia DATE,
    data_rozpoczecia DATE,
    data_zakonczenia DATE,
    czas_nieokreslony INTEGER DEFAULT 0,
    okres_wypowiedzenia VARCHAR(100),
    wartosc_umowy DECIMAL(12,2),
    waluta VARCHAR(10) DEFAULT 'PLN',
    warunki_finansowe TEXT,
    numer_projektu VARCHAR(255),
    opiekun VARCHAR(255),
    dzialania_cykliczne INTEGER DEFAULT 0,
    dzialania_opis TEXT,
    data_przegladu DATE,
    forma_podpisania VARCHAR(20),
    platforma_el VARCHAR(100),
    id_dokumentu_el VARCHAR(255),
    plik_potwierdzenia VARCHAR(500),
    plik_umowy VARCHAR(500),
    zalaczniki VARCHAR(1000),
    uwagi TEXT,
    nr_roboczy VARCHAR(100),
    nr_system VARCHAR(100),
    nr_rejestru VARCHAR(100),
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- SETTINGS
CREATE TABLE IF NOT EXISTS settings (
    key_ VARCHAR(100) PRIMARY KEY,
    value TEXT
);
