server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular routing — wszystkie ścieżki → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Długi cache dla plików z hash w nazwie
    location ~* \.(js|css|woff2?|ttf|eot|svg|png|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Brak cache dla index.html
    location = /index.html {
        add_header Cache-Control "no-store";
    }
}
